name: Test Tools Docker
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+\+java[0-9]+' # ex. v1.0.0+java1
      - 'v0.0.1-rc[0-9]+\+java[0-9]+' # used for testing only

jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - name: echo
        run: |
          echo here we are
